USE FinanceiroPessoal;
GO
SELECT 
    COLUMN_NAME, 
    DATA_TYPE, 
    CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'STG'
  AND TABLE_NAME = 'TB_STAGE_SAIDAS_ANALITICO';

USE FinanceiroPessoal;
GO
USE FinanceiroPessoal
SELECT * FROM STG.TB_STAGE_SAIDAS_ANALITICO;
GO