-- Criação da minha Stage para Saídas
USE FinanceiroPessoal;
GO

CREATE TABLE STG.TB_STAGE_SAIDAS_ANALITICO (
    DATA_ABERTURA_CARTAO DATE          NULL,
    DATA_FECHAMENTO      DATE          NULL,
    DATA_LANCAMENTO      DATE          NOT NULL,
    ID_SAIDA             INT           NOT NULL,
    BANCO                NVARCHAR(100) NULL,
    TIPO_CONTA           NVARCHAR(100) NULL,
    PLANO_CONTA          NVARCHAR(200) NULL,
    OBSERVACAO           NVARCHAR(500) NULL,
    PARCELA_ATUAL        INT           NULL,
    QTD_PARCELAS         INT           NULL,
    VALOR                DECIMAL(18,2) NOT NULL,
    SOURCE_FILE          NVARCHAR(260) NULL, -- NOME DO ARQUIVO EXCEL
    LOAD_DTTM            DATETIME2(3)  NOT NULL DEFAULT SYSUTCDATETIME()
);
GO

-- Criação da minha ODS para Saídas
USE FINANCEIROPESSOAL;
GO

CREATE TABLE ODS.TB_ODS_SAIDAS_ANALITICO (
    NR_ID_SAIDA INT NOT NULL PRIMARY KEY,
    DT_ABERTURA_CARTAO DATE NULL,
    DT_FECHAMENTO DATE NULL,
    DT_LANCAMENTO DATE NOT NULL,
    NM_BANCO NVARCHAR(100) NULL,
    NM_TIPO_CONTA NVARCHAR(100) NULL,
    NM_PLANO_CONTA NVARCHAR(200) NULL,
    NM_OBSERVACAO NVARCHAR(500) NULL,
    NR_PARCELA_ATUAL INT NULL,
    NR_QTD_PARCELAS INT NULL,
    NR_VALOR DECIMAL(18,2) NOT NULL,
    NM_SOURCE_FILE NVARCHAR(260) NULL,
    DT_LOAD DATETIME2(3) NOT NULL DEFAULT SYSDATETIME()
);
GO