-- Criação da minha ODS para entradas:
USE FinanceiroPessoal;
GO

CREATE TABLE ODS.TB_ODS_ENTRADAS_ANALITICO(
    NR_ID_ENTRADA INT NOT NULL PRIMARY KEY,
    DT_ENTRADA DATE NULL,
    NM_BANCO NVARCHAR(100) NULL,
    NM_TIPO_ENTRADA NVARCHAR(100) NULL,
    NM_PLANO_CONTA NVARCHAR(100) NULL,
    NM_OBSERVACAO NVARCHAR(200) NULL,
    NR_VALOR DECIMAL (18,2) NOT NULL,
    NM_SOURCE_FILE NVARCHAR(260) NULL,
    DT_LOAD DATETIME2(3) NOT NULL DEFAULT SYSDATETIME()
)

-- Criação da minha ODS para Saídas
USE FinanceiroPessoal;
GO

CREATE TABLE ODS.TB_ODS_SAIDAS_ANALITICO (
    NR_ID_SAIDA INT NOT NULL PRIMARY KEY,
    DT_ABERTURA_CARTAO DATE NULL,
    DT_FECHAMENTO DATE NULL,
    DT_LANCAMENTO DATE NOT NULL,
    NM_BANCO NVARCHAR(100) NULL,
    NM_TIPO_CONTA NVARCHAR(100) NULL,
    NM_PLANO_CONTA NVARCHAR(200) NULL,
    NM_OBSERVACAO NVARCHAR(500) NULL,
    NR_PARCELA_ATUAL INT NULL,
    NR_QTD_PARCELAS INT NULL,
    NR_VALOR DECIMAL(18,2) NOT NULL,
    NM_SOURCE_FILE NVARCHAR(260) NULL,
    DT_LOAD DATETIME2(3) NOT NULL DEFAULT SYSDATETIME()
);
GO
 
-- Criação da minha tabela dimensão Tempo
USE FinanceiroPessoal;
GO

CREATE TABLE DIM.DIM_TEMPO (
    DT_DATA DATE NOT NULL PRIMARY KEY,
    NR_ANO INT NOT NULL,
    NR_MES INT NOT NULL,
    NM_MES NVARCHAR(20) NOT NULL,
    NR_DIA INT NOT NULL,
    NM_DIA_SEMANA NVARCHAR(20) NOT NULL,
    NR_TRIMESTRE INT NOT NULL,
    NR_SEMANA_MES INT NOT NULL
);
GO

-- ===============================
-- DIM_BANCO
-- ===============================
USE FinanceiroPessoal;
GO

CREATE TABLE DIM.DIM_BANCO (
    ID_BANCO INT IDENTITY(1,1) PRIMARY KEY,
    NM_BANCO NVARCHAR(100) NOT NULL
);
GO

-- ===============================
-- DIM_TIPO_CONTA
-- ===============================
USE FinanceiroPessoal;
GO

CREATE TABLE DIM.DIM_TIPO_CONTA (
    ID_TIPO_CONTA INT IDENTITY(1,1) PRIMARY KEY,
    NM_TIPO_CONTA NVARCHAR(100) NOT NULL
);
GO

-- ===============================
-- DIM_PLANO_CONTA
-- ===============================
USE FinanceiroPessoal;
GO

CREATE TABLE DIM.DIM_PLANO_CONTA (
    ID_PLANO_CONTA INT IDENTITY(1,1) PRIMARY KEY,
    NM_PLANO_CONTA NVARCHAR(200) NOT NULL
);
GO